export enum BookActionTypes {
  GET_BOOKS_REQUEST = 'GET_BOOKS_REQUEST',
  GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS',
  GET_BOOKS_FAIL = 'GET_BOOKS_FAIL',
  GET_BOOKS_RESET = 'GET_BOOKS_RESET',

  ADD_BOOK_FAVORITE_REQUEST = 'ADD_BOOK_FAVORITE_REQUEST',
  ADD_BOOK_FAVORITE_SUCCESS = 'ADD_BOOK_FAVORITE_SUCCESS',
  ADD_BOOK_FAVORITE_FAIL = 'ADD_BOOK_FAVORITE_FAIL',

  REMOVE_BOOK_FAVORITE_REQUEST = 'REMOVE_BOOK_FAVORITE_REQUEST',
  REMOVE_BOOK_FAVORITE_SUCCESS = 'REMOVE_BOOK_FAVORITE_SUCCESS',
  REMOVE_BOOK_FAVORITE_FAIL = 'REMOVE_BOOK_FAVORITE_FAIL',

  GET_BOOK_FAVORITES_REQUEST = 'GET_BOOK_FAVORITES_REQUEST',
  GET_BOOK_FAVORITES_SUCCESS = 'GET_BOOK_FAVORITES_SUCCESS',
  GET_BOOK_FAVORITES_FAIL = 'GET_BOOK_FAVORITES_FAIL',
}
